// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestxxClient is the client API for Testxx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestxxClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type testxxClient struct {
	cc grpc.ClientConnInterface
}

func NewTestxxClient(cc grpc.ClientConnInterface) TestxxClient {
	return &testxxClient{cc}
}

func (c *testxxClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxxx.tsetxx.Testxx/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestxxServer is the server API for Testxx service.
// All implementations must embed UnimplementedTestxxServer
// for forward compatibility
type TestxxServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTestxxServer()
}

// UnimplementedTestxxServer must be embedded to have forward compatible implementations.
type UnimplementedTestxxServer struct {
}

func (UnimplementedTestxxServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTestxxServer) mustEmbedUnimplementedTestxxServer() {}

// UnsafeTestxxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestxxServer will
// result in compilation errors.
type UnsafeTestxxServer interface {
	mustEmbedUnimplementedTestxxServer()
}

func RegisterTestxxServer(s grpc.ServiceRegistrar, srv TestxxServer) {
	s.RegisterService(&Testxx_ServiceDesc, srv)
}

func _Testxx_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestxxServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxxx.tsetxx.Testxx/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestxxServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Testxx_ServiceDesc is the grpc.ServiceDesc for Testxx service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Testxx_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxxx.tsetxx.Testxx",
	HandlerType: (*TestxxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Testxx_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Testxx.proto",
}
