// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SddtestXXXXClient is the client API for SddtestXXXX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SddtestXXXXClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type sddtestXXXXClient struct {
	cc grpc.ClientConnInterface
}

func NewSddtestXXXXClient(cc grpc.ClientConnInterface) SddtestXXXXClient {
	return &sddtestXXXXClient{cc}
}

func (c *sddtestXXXXClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/aaaaa.sddtestxxxx.SddtestXXXX/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SddtestXXXXServer is the server API for SddtestXXXX service.
// All implementations must embed UnimplementedSddtestXXXXServer
// for forward compatibility
type SddtestXXXXServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedSddtestXXXXServer()
}

// UnimplementedSddtestXXXXServer must be embedded to have forward compatible implementations.
type UnimplementedSddtestXXXXServer struct {
}

func (UnimplementedSddtestXXXXServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSddtestXXXXServer) mustEmbedUnimplementedSddtestXXXXServer() {}

// UnsafeSddtestXXXXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SddtestXXXXServer will
// result in compilation errors.
type UnsafeSddtestXXXXServer interface {
	mustEmbedUnimplementedSddtestXXXXServer()
}

func RegisterSddtestXXXXServer(s grpc.ServiceRegistrar, srv SddtestXXXXServer) {
	s.RegisterService(&SddtestXXXX_ServiceDesc, srv)
}

func _SddtestXXXX_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SddtestXXXXServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aaaaa.sddtestxxxx.SddtestXXXX/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SddtestXXXXServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SddtestXXXX_ServiceDesc is the grpc.ServiceDesc for SddtestXXXX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SddtestXXXX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aaaaa.sddtestxxxx.SddtestXXXX",
	HandlerType: (*SddtestXXXXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SddtestXXXX_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SddtestXXXX.proto",
}
